import { asc } from "drizzle-orm";
import { getDb } from "../../../../db";
import { orderItems, orders } from "../../../../db/schema";
import { requireAdministrator } from "../../../../lib/access";

function csvCell(value: unknown) {
  let text = String(value ?? "");
  if (/^[=+\-@]/.test(text)) text = `'${text}`;
  return `"${text.replace(/"/g, '""')}"`;
}

export async function GET(request: Request) {
  try {
    const auth = await requireAdministrator(request);
    if (auth.error) return auth.error;
    const email = auth.access.email;

    const url = new URL(request.url);
    const currentYear = new Date().getUTCFullYear();
    const requestedYear = Number(url.searchParams.get("year"));
    const year = Number.isInteger(requestedYear) && requestedYear >= 2000 && requestedYear <= 2100 ? requestedYear : currentYear;
    const requestedType = url.searchParams.get("type") || "All";
    const allowedTypes = ["BOM", "Stock Request", "Customer Order"] as const;
    const requestType = allowedTypes.includes(requestedType as (typeof allowedTypes)[number]) ? requestedType : "All";
    const db = getDb();
    const orderRows = (await db.select().from(orders).orderBy(asc(orders.orderDate))).filter((order) => order.orderDate.startsWith(`${year}-`) && (requestType === "All" || order.requestType === requestType));
    const itemRows = await db.select().from(orderItems);
    const orderIds = new Set(orderRows.map((order) => order.id));
    const reportItems = itemRows.filter((item) => orderIds.has(item.orderId));
    const counts = { BOM: 0, "Stock Request": 0, "Customer Order": 0 } as Record<string, number>;
    for (const order of orderRows) counts[order.requestType] = (counts[order.requestType] || 0) + 1;

    const rows: unknown[][] = [
      ["OrderFlow Order Tracking — Yearly Report"],
      ["Year", year],
      ["Request Type Filter", requestType === "All" ? "All Orders" : requestType],
      ["Generated by", email],
      ["Generated on", new Date().toISOString()],
      [],
      ["Summary"],
      ["Request Type", "Orders"],
      ["BOM", counts.BOM],
      ["Stock Request", counts["Stock Request"]],
      ["Customer Order", counts["Customer Order"]],
      ["Total", orderRows.length],
      [],
      ["Request Type", "Website Lead", "Order Number", "Order Date / Invoice Date", "Client", "Sales Person / Requestor", "Project Number", "PI Number", "Quotation Number", "Customer PO", "Overall / Latest Delivery", "Order Status", "Item Description", "Barcode", "Customer Reference", "Lead Time", "Item Planned Delivery", "Qty Required", "Qty in Stock", "Qty to Order", "Units", "Selling Price incl. VAT", "Submitted By", "Submitted Email"],
    ];

    for (const order of orderRows) {
      const items = reportItems.filter((item) => item.orderId === order.id);
      if (!items.length) items.push({} as typeof reportItems[number]);
      for (const item of items) rows.push([order.requestType, order.websiteLead ? "Yes" : "No", order.orderNumber, order.orderDate, order.clientName, order.salesPerson, order.projectNumber, order.piNumber, order.quotationNumber, order.customerPoNumber, order.plannedDeliveryDate, order.status, item.description, item.barcode, item.customerReference || order.customerReference, item.leadTime, item.plannedDeliveryDate, item.qtyRequired, item.qtyInStock, item.qtyToOrder, item.units, item.sellingPrice, order.submittedByName, order.submittedByEmail]);
    }

    const csv = `\uFEFF${rows.map((row) => row.map(csvCell).join(",")).join("\r\n")}`;
    const typeSlug = requestType === "All" ? "All_Orders" : requestType.replace(/\s+/g, "_");
    return new Response(csv, { headers: { "Content-Type": "text/csv; charset=utf-8", "Content-Disposition": `attachment; filename="OrderFlow_Order_Report_${year}_${typeSlug}.csv"`, "Cache-Control": "no-store" } });
  } catch (error) {
    return Response.json({ error: error instanceof Error ? error.message : "Could not create the report" }, { status: 500 });
  }
}
